package blockchain

import (
	"crypto/x509"
	"fmt"
	"io/ioutil"
	"path/filepath"

	"github.com/hyperledger/fabric-gateway/pkg/client"
	"github.com/hyperledger/fabric-gateway/pkg/identity"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

type FabricClient struct {
	Contract *client.Contract
}

func NewFabricClient() (*FabricClient, error) {
	// Load the connection profile;
	// Use the Admin identity that was generated by the test-network so the MSP matches the peer's MSP
	certPath := filepath.Join("..", "test-network", "organizations", "peerOrganizations", "org1.example.com", "users", "Admin@org1.example.com", "msp", "signcerts", "cert.pem")
	keyDir := filepath.Join("..", "test-network", "organizations", "peerOrganizations", "org1.example.com", "users", "Admin@org1.example.com", "msp", "keystore")
	tlscertPath := filepath.Join("..", "test-network", "organizations", "peerOrganizations", "org1.example.com", "peers", "peer0.org1.example.com", "tls", "ca.crt")

	// Load Certificate
	certPem, err := ioutil.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("Failed to read certificate: %v", err)
	}

	cert, err := identity.CertificateFromPEM(certPem)
	if err != nil {
		return nil, fmt.Errorf("Failed to parse certificate: %v", err)
	}

	id, err := identity.NewX509Identity("Org1MSP", cert)
	if err != nil {
		return nil, fmt.Errorf("Failed to create identity: %v", err)
	}

	// Load Private Key
	files, _ := ioutil.ReadDir(keyDir)
	keyPath := filepath.Join(keyDir, files[0].Name())

	keyPem, err := ioutil.ReadFile(keyPath)
	privateKey, err := identity.PrivateKeyFromPEM(keyPem)

	sign, err := identity.NewPrivateKeySign(privateKey)

	// Load TLS Certificate
	caCert, err := ioutil.ReadFile(tlscertPath)
	certPool := x509.NewCertPool()
	certPool.AppendCertsFromPEM(caCert)

	creds := credentials.NewClientTLSFromCert(certPool, "")

	conn, err := grpc.Dial("localhost:7051", grpc.WithTransportCredentials(creds))
	if err != nil {
		return nil, fmt.Errorf("Failed to connect to gateway: %v", err)
	}

	gw, err := client.Connect(id, client.WithSign(sign), client.WithClientConnection(conn))
	if err != nil {
		return nil, fmt.Errorf("Failed to connect to gateway: %v", err)
	}

	network := gw.GetNetwork("mychannel")
	contract := network.GetContract("koperasi")

	return &FabricClient{Contract: contract}, nil
}